title: ember-cordova
description: "docs for ember cordova"
author: Isle of Code
url: "http://embercordova.com"
baseurl: ''
twitter_username: isleOfCode
github_username:  isleOfCode
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
